name: stash_android
description: An Android app for storing contacts outside the phone's contact list.
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  get_it: ^7.6.7
  equatable: ^2.0.7
  provider: ^6.1.2
  rxdart: ^0.27.7
  flutter_dialog_manager: ^1.0.0+4
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  flutter_gen_runner:

flutter_gen:
  output: lib/core/assets
  assets:
    outputs:
      class_name: StashAssets
      package_parameter_enabled: false

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
